### ISSUE TITLE
autoencoder.api.autoencode doesn't work

### ISSUE THREAD

**Issue by jacksonloper** [gokceneraslan/countae#1]
Hi there.  Saw you at NIPS.  Trying to get this thing going on my data.

`autoencoder.api.autoencode` seems to have a bug.  If I have a numpy array of cells by genes, what is the most straightforward way to run your method on my data?  Thanks!

**Comment by gokceneraslan** [comment]
Hey @jacksonloper,

Sorry for late response. Can you try installing the latest version:

pip install git+https://github.com/gokceneraslan/autoencoder

and then running the following command:

`autoencoder genexcellmatrix.tsv results`

command and have a look at `results/mean.tsv`matrix?

**Comment by gokceneraslan** [comment]
API is still outdated, we are focusing on implementing an easy-to-use command line tool. But I'll also improve the API at some point.

**Comment by gokceneraslan** [comment]
I updated the API and added a tutorial, see README.md
